---
info:
  title: "VWF & AFrame Example App"
model:
  vwf/model/aframe:
view:
  vwf/view/aframe:
  vwf/view/editor-new:
  vwf/view/webrtc: { iceServers: [ { url: 'stun:stun.l.google.com:19302' }, { url: 'stun:stun1.l.google.com:19302' },  { url: 'stun:stun2.l.google.com:19302' }, { url: 'stun:stun3.l.google.com:19302' }] }